# Generated by Django 3.0.5 on 2020-11-15 17:46

import Graffiti.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionBien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('localizacion', models.CharField(max_length=50)),
                ('tematica', djongo.models.fields.JSONField()),
                ('autor', models.CharField(max_length=50)),
                ('listaGraffiti', djongo.models.fields.ArrayField(model_container=Graffiti.models.Graffiti)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graffiti.Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraffitiBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField()),
                ('estado', models.CharField(max_length=30)),
                ('fechaCaptura', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graffiti_graffitibien_related', related_query_name='graffiti_graffitibien_s', to='Graffiti.Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComentarioBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graffiti_comentariobien_related', related_query_name='graffiti_comentariobien_s', to='Graffiti.Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
