# Generated by Django 3.0.5 on 2020-11-16 11:19

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('psw', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('seguidores', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graffiti_usuario_seguidores', to='Graffiti.Usuario')),
                ('seguidos', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graffiti_usuario_seguidos', to='Graffiti.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('publicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graffiti_publicacion_creador', to='Graffiti.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Graffiti',
            fields=[
                ('graffiti_id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graffiti_graffiti_autor', to='Graffiti.Usuario')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graffiti.Publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graffiti_comentario_autor', to='Graffiti.Usuario')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graffiti.Publicacion')),
            ],
        ),
    ]
