# Generated by Django 3.0.5 on 2020-11-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graffiti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionbien',
            name='tematica',
        ),
    ]
