# Generated by Django 3.0.5 on 2020-11-16 11:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Graffiti', '0002_auto_20201116_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='texto',
            field=models.CharField(default='hola', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graffiti',
            name='estado',
            field=models.CharField(default='ok', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graffiti',
            name='fechaCaptura',
            field=models.DateField(default=datetime.datetime(2020, 11, 16, 11, 58, 52, 297378, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graffiti',
            name='imagen',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='localizacion',
            field=models.CharField(default='localizacion', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tematica',
            field=djongo.models.fields.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Graffiti.Publicacion'),
        ),
        migrations.AlterField(
            model_name='graffiti',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graffitis', to='Graffiti.Publicacion'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='Graffiti.Usuario'),
        ),
    ]
