# Generated by Django 3.0.5 on 2020-11-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graffiti', '0003_auto_20201116_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='Graffiti.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(blank=True, null=True, related_name='reverse_seguidores', to='Graffiti.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='seguidos',
            field=models.ManyToManyField(blank=True, null=True, related_name='reverse_seguidos', to='Graffiti.Usuario'),
        ),
    ]
